stages:
  - build

build:
  stage: build
  image: microsoft/dotnet:sdk
  script:
    - chmod +x zero29.sh
    - ./zero29.sh -i minor
    - ./zero29.sh -l
    - cd src/LeagueOfMonads.Core
    - dotnet build
    - cd ../..
    - ./zero29.sh -l