stages:
  - build

build:
  stage: build
  image: microsoft/dotnet:sdk
  script:
    - wget https://github.com/adleatherwood/ZeroToNine/releases/download/v1.1.0/zero29.sh
    - chmod +x zero29.sh
    - ./zero29.sh -i minor    
    - cd src/LeagueOfMonads.Core
    - dotnet build    