image: microsoft/dotnet:latest

stages:
  - test
  - build
  - release

test:branch:
  stage: test
  except:
    - /master/
    - /develop/
  script:
    - ./build.sh
      build-debug
      run-tests

build:develop:
 stage: build
 only: 
   - /develop/
 script:
   - ./build.sh 
     build-debug 
     run-tests
 artifacts:
   paths:
     - ./src/LeagueOfMonads.Core/bin/Debug/netstandard2.0/*.*

release:master:
  stage: release
  only: 
    - /master/
  script:
    - ./build.sh 
      download-semrel
      download-ezrep
      build-debug 
      run-tests 
      build-release 
      package-release
      publish-release
      tag-release
